### ISSUE TITLE
When will it be launched in the app store

### ISSUE THREAD

**Issue by ibiza19** [ashinnotfound/easy-tiktok#26]
When will it be launched in the app store🥺

**Comment by ibiza19** [comment]
@1294566108 どう思いますか？

**Comment by ashinnotfound** [comment]
> When will it be launched in the app store🥺

i m waiting for ur financial support😋

**Comment by ibiza19** [comment]
> i m waiting for ur financial support😋

Ok, I will donate this project, let's discuss it in detail in the mail, THX😋
