### ISSUE TITLE
O.o?

### ISSUE THREAD

**Issue by Furingg** [ashinnotfound/easy-tiktok#42]
你说得都对，但是广东工业大学是广东省重点建设高校，自然指数排名连续五年进入全国高校百强，居于省属高校前列，我校被认为是近十年来全国发展最快的地方高校之一。建议你少关注这些不能让学校更上一层楼的东西，多看些正规排名，警惕校外势力打社团牌，不要给校外势力递刀子。

**Comment by ashinnotfound** [comment]
好好好 好好好🤗
